### ISSUE TITLE
Client Side JS- Convert to ES6 modules

### ISSUE THREAD

**Issue by njsfield** [njsfield/mysite#36]
- [x] Create *functional* branch
- [x] Purify functions
- [x] Build directory structure, create *js* directory in src, move main app file there, move functions to helpers.
- [x] Install webpack, create webpack.config.js file, and webpack-build.js file.
- [x] Install babel loader (and babel modules), create .babelrc file
- [x] Install minify loader
- [x] Build app to public/js
