### ISSUE TITLE
Store Images in DB

### ISSUE THREAD

**Issue by njsfield** [njsfield/mysite#45]
Images are mostly low-size svgs, therefore instead of storing on the server, store as globs (type string) in the database.
- [x] Create new db-images branch
- [x] Rebuild database query
- [x] Rebuild images route to store in database
- [x] Modify /image directory route (and in views) to query image content (use 'image/' instead of /images/)
