### ISSUE TITLE
Display Post Titles In Urls

### ISSUE THREAD

**Issue by njsfield** [njsfield/mysite#49]
Currently blog post ids are being used to display, edit and update posts. 
Add functionality so that when submitting post;
- [x] On sql table, add column for url
- [x] On compose route, chop off first ten words from title, sanitize so url friendly, then save as post.url in table
- [x] For blog post view, add uri to end of post
- [x] On route for blog/portfolio/edit, on get request, use post url instead of postid
- [x] On edit route, on post request, chop off first ten words, sanitize so url friendly, then
- [x] On update post query, update url too
